--Triage:Malade,Préconsultation,Rapports,Personne,Aptitude physique
revoke select,insert,update,delete on personne to p
revoke select,insert,update,delete on aptitudephysique to p
revoke select,insert,update,delete on province to p
revoke select,insert,update,delete on districtville to p
revoke select,insert,update,delete on territoirecommune to p
revoke select,insert,update,delete on collectivitequartier to p
revoke select,insert,update,delete on categoriemalade to p
revoke select,insert,update,delete on profession to p
revoke select,insert,update,delete on etablissementpriseencharge to p
revoke select,insert,update,delete on groupesanguin to p
revoke select,insert,update,delete on malade to p
revoke select,insert,update,delete on dossierpreconsultation to p
revoke select,insert,update,delete on preconsultation to p
revoke select,insert,update,delete on airsante to p
revoke select on consultation to p
revoke select on mouvementconsultation to p
revoke select on operation_laboratoire to p
revoke select on critereresultat to p
revoke select on examen to p
revoke select on typeexamen to p
revoke select on hospitalisation to p
revoke select on mvmhospitalisation to p
revoke select on chambre to p
revoke select on categoriechambre to p
revoke select on intervention to p
revoke select on subit to p
revoke select on bloc to p
revoke select on criterechographie to p
revoke select on consultationgynecologique to p
revoke select on tarifconsultationgynecologique to p
revoke select on dossierconsultationgynecologique to p
revoke select on article to p
revoke select on service to p
revoke select on autrefraie to p
revoke select on etablissementexterne to p
revoke select on detailsautrefraie to p
revoke select on dossierconsultationprenatale to p
revoke select on consultationprenatal to p
revoke select on dossierconsultationpostnatal to p
revoke select on maladeenconsultationpostnatal to p
revoke select on tarifechographie to p
revoke select on dossierechographie to p
revoke select on tarifsoin to p
revoke select on dossiersoin to p
revoke select on tarifnursing to p
revoke select on dossiernursing to p
revoke select on dossieraccouchement to p
revoke select on typeaccouchement to p
revoke select on tarifavance to p
revoke select on dossieravance to p
revoke select on mouvementoperation_laboratoire to p
revoke select on tarifpreconsultation to p
revoke select on sortie to p

--Medécin:Malade,Préconsultation,Rapports,Personne,Aptitude physique,Consultation normale, Hospitalisation,Intervention
revoke select,insert,update,delete on personne to p
revoke select,insert,update,delete on aptitudephysique to p
revoke select,insert,update,delete on province to p
revoke select,insert,update,delete on districtville to p
revoke select,insert,update,delete on territoirecommune to p
revoke select,insert,update,delete on collectivitequartier to p
revoke select,insert,update,delete on categoriemalade to p
revoke select,insert,update,delete on profession to p
revoke select,insert,update,delete on etablissementpriseencharge to p
revoke select,insert,update,delete on groupesanguin to p
revoke select,insert,update,delete on malade to p
revoke select,insert,update,delete on dossierpreconsultation to p
revoke select,insert,update,delete on preconsultation to p
revoke select on consultation to p
revoke select on mouvementconsultation to p
revoke select on operation_laboratoire to p
revoke select on critereresultat to p
revoke select on examen to p
revoke select on typeexamen to p
revoke select on hospitalisation to p
revoke select on mvmhospitalisation to p
revoke select on chambre to p
revoke select on categoriechambre to p
revoke select on intervention to p
revoke select on subit to p
revoke select on bloc to p
revoke select on criterechographie to p
revoke select on consultationgynecologique to p
revoke select on tarifconsultationgynecologique to p
revoke select on dossierconsultationgynecologique to p
revoke select on article to p
revoke select on service to p
revoke select on autrefraie to p
revoke select on etablissementexterne to p
revoke select on detailsautrefraie to p
revoke select on dossierconsultationprenatale to p
revoke select on consultationprenatal to p
revoke select on dossierconsultationpostnatal to p
revoke select on maladeenconsultationpostnatal to p
revoke select on tarifechographie to p
revoke select on dossierechographie to p
revoke select on tarifsoin to p
revoke select on dossiersoin to p
revoke select on tarifnursing to p
revoke select on dossiernursing to p
revoke select on dossieraccouchement to p
revoke select on typeaccouchement to p
revoke select on tarifavance to p
revoke select on dossieravance to p
revoke select on mouvementoperation_laboratoire to p
revoke select on agent to p
revoke select on tarifpreconsultation to p

--
revoke select,insert,update,delete on examen to p
revoke select,insert,update,delete on typeexamen to p
revoke select,insert,update,delete on maladie to p 
revoke select,insert,update,delete on maladie to p 
revoke select,insert,update,delete on mouvementmaladie to p
revoke select,insert,update,delete on mouvementconsultation to p
revoke update on consultation to p
revoke select,insert,update,delete on hospitalisation to p
revoke select,insert,update,delete on chambre to p
revoke select,insert,update,delete on mvmhospitalisation to p
revoke select,insert,update,delete on subit to p
revoke select,insert,update,delete on airsante to p
revoke select on sortie to p
grant select on tarifconsultation to p

--Medécin gynécologue:Malade,Préconsultation,Rapports,Personne,Aptitude physique,Consultation normale,Consultation gynéco, Hospitalisation,Intervention
revoke select,insert,update,delete on personne to p
revoke select,insert,update,delete on aptitudephysique to p
revoke select,insert,update,delete on province to p
revoke select,insert,update,delete on districtville to p
revoke select,insert,update,delete on territoirecommune to p
revoke select,insert,update,delete on collectivitequartier to p
revoke select,insert,update,delete on categoriemalade to p
revoke select,insert,update,delete on profession to p
revoke select,insert,update,delete on etablissementpriseencharge to p
revoke select,insert,update,delete on groupesanguin to p
revoke select,insert,update,delete on malade to p
revoke select,insert,update,delete on dossierpreconsultation to p
revoke select,insert,update,delete on preconsultation to p
revoke select on consultation to p
revoke select on mouvementconsultation to p
revoke select on operation_laboratoire to p
revoke select on critereresultat to p
revoke select on examen to p
revoke select on typeexamen to p
revoke select on hospitalisation to p
revoke select on mvmhospitalisation to p
revoke select on chambre to p
revoke select on categoriechambre to p
revoke select on intervention to p
revoke select on subit to p
revoke select on bloc to p
revoke select on criterechographie to p
revoke select on consultationgynecologique to p
revoke select on tarifconsultationgynecologique to p
revoke select on dossierconsultationgynecologique to p
revoke select on article to p
revoke select on service to p
revoke select on autrefraie to p
revoke select on etablissementexterne to p
revoke select on detailsautrefraie to p
revoke select on dossierconsultationprenatale to p
revoke select on consultationprenatal to p
revoke select on dossierconsultationpostnatal to p
revoke select on maladeenconsultationpostnatal to p
revoke select on tarifechographie to p
revoke select on dossierechographie to p
revoke select on tarifsoin to p
revoke select on dossiersoin to p
revoke select on tarifnursing to p
revoke select on dossiernursing to p
revoke select on dossieraccouchement to p
revoke select on typeaccouchement to p
revoke select on tarifavance to p
revoke select on dossieravance to p
revoke select on mouvementoperation_laboratoire to p
revoke select on agent to p
revoke select on tarifpreconsultation to p
revoke select on sortie to p

--
revoke select,insert,update,delete on examen to p
revoke select,insert,update,delete on typeexamen to p
revoke select,insert,update,delete on maladie to p 
revoke select,insert,update,delete on maladie to p 
revoke select,insert,update,delete on mouvementmaladie to p
revoke select,insert,update,delete on mouvementconsultation to p
revoke update on consultation to p
revoke select,insert,update,delete on hospitalisation to p
revoke select,insert,update,delete on chambre to p
revoke select,insert,update,delete on mvmhospitalisation to p
revoke select,insert,update,delete on subit to p
revoke select,insert,update,delete on airsante to p

--
revoke select,insert,update,delete on criterechographie to p
revoke select,insert,update,delete on consultationgynecologique to p

--Pharmacie:Personne,Fournisseur,Approvisionnement,Sortie articles,Rapports
revoke select,insert,update,delete on personne to p
revoke select,insert,update,delete on fournisseur to p
revoke select,insert,update,delete on article to p
revoke select,insert,update,delete on livraison to p
revoke select,insert,update,delete on sortie to p
revoke select,insert,update,delete on sortiecancel to p
revoke select,insert,update,delete on conditionnement to p
revoke select,insert,update,delete on fournisseur to p
revoke select on malade to p
revoke select on agent to p
revoke select on service to p

--Laboratoire:Examen,Rapports
revoke select on personne to p
revoke select on malade to p
revoke select on agent to p
revoke select on examen to p
revoke select on typeexamen to p
revoke select,update on operation_laboratoire to p
revoke select on dossierpreconsultation to p
revoke select on preconsultation to p
revoke select on consultation to p
revoke select on consultationgynecologique to p
revoke select on tarifconsultation to p
revoke select,insert,update,delete on critereresultat to p
revoke select,insert,update,delete on mouvementoperation_laboratoire to p 

--Caisse:Paiement,Approvisionnement,Sortie article,Tarifs,avance,Rapport
revoke insert,update,delete on personne to p
revoke select,insert,update,delete on autrefraie to p
revoke select,insert,update,delete on detailsautrefraie to p
revoke select,insert,update,delete on article to p
revoke select,insert,update,delete on operation_laboratoire to p
revoke select,insert,update,delete on tarifconsultationpostnatal to p
revoke select,insert,update,delete on tarifconsultationprenatal to p
revoke select,insert,update,delete on tarifconsultation to p
revoke select,insert,update,delete on tarifpreconsultation to p
revoke select,insert,update,delete on tarifconsultationgynecologique to p
revoke select,insert,update,delete on intervention to p
revoke select,insert,update,delete on chambre to p
revoke select,insert,update,delete on categoriechambre to p
revoke select,insert,update,delete on typeaccouchement to p
revoke select,insert,update,delete on tarifechographie to p
revoke select,insert,update,delete on tarifsoin to p
revoke select,insert,update,delete on tarifnursing to p
revoke select,insert,update,delete on tarifavance to p
revoke select,insert,update,delete on paiement to p
revoke select,insert,update,delete on article_paye to p
revoke select,insert,update,delete on facturation to p
revoke select,insert,update,delete on sortie to p
revoke select,insert,update,delete on sortiecancel to p
revoke select,insert,update,delete on dossierpreconsultation to p
revoke select,insert,update,delete on consultation to p
revoke select,insert,update,delete on dossierconsultationprenatale to p
revoke select,insert,update,delete on dossierconsultationpostnatal to p
revoke select,insert,update,delete on operation_laboratoire to p
revoke select,insert,update,delete on subit to p
revoke select,insert,update,delete on dossierconsultationgynecologique to p
revoke select,insert,update,delete on dossieraccouchement to p
revoke select,insert,update,delete on dossierechographie to p
revoke select,insert,update,delete on dossiersoin to p
revoke select,insert,update,delete on dossiernursing to p
revoke select,insert,update,delete on dossieravance to p
revoke select,insert,update,delete on hospitalisation to p
revoke select,insert,update,delete on bloc to p
revoke select,insert,update,delete on service to p
revoke select,insert,update,delete on etablissementexterne to p
revoke select,insert,update,delete on etablissementpriseencharge to p
revoke select on aptitudephysique to p
revoke select on province to p
revoke select on districtville to p
revoke select on territoirecommune to p
revoke select on collectivitequartier to p
revoke select on categoriemalade to p
revoke select on profession to p
revoke select on groupesanguin to p
revoke select on malade to p
revoke select on categoriemalade to p
revoke select on airsante to p


--Service:Sortie article (select et insert)
revoke select,insert,update,delete on article to p
revoke select,insert on sortie to p
revoke select,insert,update,delete on sortiecancel to p
revoke select on conditionnement to p
revoke select on fournisseur to p
revoke select on malade to p
revoke select on agent to p
revoke select on service to p