--Triage:Malade,Préconsultation,Rapports,Personne,Aptitude physique
grant select,insert,update,delete on personne to p
grant select,insert,update,delete on aptitudephysique to p
grant select,insert,update,delete on province to p
grant select,insert,update,delete on districtville to p
grant select,insert,update,delete on territoirecommune to p
grant select,insert,update,delete on collectivitequartier to p
grant select,insert,update,delete on categoriemalade to p
grant select,insert,update,delete on profession to p
grant select,insert,update,delete on etablissementpriseencharge to p
grant select,insert,update,delete on groupesanguin to p
grant select,insert,update,delete on malade to p
grant select,insert,update,delete on dossierpreconsultation to p
grant select,insert,update,delete on fichesupplementaire to p
grant select,insert,update,delete on preconsultation to p
grant select,insert,update,delete on airsante to p
grant select on consultation to p
grant select on mouvementconsultation to p
grant select on operation_laboratoire to p
grant select on critereresultat to p
grant select on examen to p
grant select on typeexamen to p
grant select on hospitalisation to p
grant select on mvmhospitalisation to p
grant select on chambre to p
grant select on categoriechambre to p
grant select on intervention to p
grant select on subit to p
grant select on bloc to p
grant select on criterechographie to p
grant select on consultationgynecologique to p
grant select on tarifconsultationgynecologique to p
grant select on dossierconsultationgynecologique to p
grant select on article to p
grant select on service to p
grant select on autrefraie to p
grant select on etablissementexterne to p
grant select on detailsautrefraie to p
grant select on dossierconsultationprenatale to p
grant select on consultationprenatal to p
grant select on dossierconsultationpostnatal to p
grant select on maladeenconsultationpostnatal to p
grant select on tarifechographie to p
grant select on dossierechographie to p
grant select on tarifsoin to p
grant select on dossiersoin to p
grant select on tarifnursing to p
grant select on dossiernursing to p
grant select on dossieraccouchement to p
grant select on typeaccouchement to p
grant select on tarifavance to p
grant select on dossieravance to p
grant select on mouvementoperation_laboratoire to p
grant select on tarifpreconsultation to p
grant select on sortie to p

--Medécin:Malade,Préconsultation,Rapports,Personne,Aptitude physique,Consultation normale, Hospitalisation,Intervention
grant select,insert,update,delete on personne to p
grant select,insert,update,delete on aptitudephysique to p
grant select,insert,update,delete on province to p
grant select,insert,update,delete on districtville to p
grant select,insert,update,delete on territoirecommune to p
grant select,insert,update,delete on collectivitequartier to p
grant select,insert,update,delete on categoriemalade to p
grant select,insert,update,delete on profession to p
grant select,insert,update,delete on etablissementpriseencharge to p
grant select,insert,update,delete on groupesanguin to p
grant select,insert,update,delete on malade to p
grant select,insert,update,delete on dossierpreconsultation to p
grant select,insert,update,delete on preconsultation to p
grant select,insert,update,delete on maladie to p
grant select,insert,update,delete on allergie to p
grant select,insert,update,delete on antecedentallergie to p
grant select,insert,update,delete on antecedentmaladie to p
grant select,insert,update,delete on fichesupplementaire to p
grant select on consultation to p
grant select on mouvementconsultation to p
grant select on operation_laboratoire to p
grant select on critereresultat to p
grant select on examen to p
grant select on typeexamen to p
grant select on hospitalisation to p
grant select on mvmhospitalisation to p
grant select on chambre to p
grant select on categoriechambre to p
grant select on intervention to p
grant select on subit to p
grant select on bloc to p
grant select on criterechographie to p
grant select on consultationgynecologique to p
grant select on tarifconsultationgynecologique to p
grant select on dossierconsultationgynecologique to p
grant select on article to p
grant select on service to p
grant select on autrefraie to p
grant select on etablissementexterne to p
grant select on detailsautrefraie to p
grant select on dossierconsultationprenatale to p
grant select on consultationprenatal to p
grant select on dossierconsultationpostnatal to p
grant select on maladeenconsultationpostnatal to p
grant select on tarifechographie to p
grant select on dossierechographie to p
grant select on tarifsoin to p
grant select on dossiersoin to p
grant select on tarifnursing to p
grant select on dossiernursing to p
grant select on dossieraccouchement to p
grant select on typeaccouchement to p
grant select on tarifavance to p
grant select on dossieravance to p
grant select on mouvementoperation_laboratoire to p
grant select on agent to p
grant select on tarifpreconsultation to p
grant select on tarifconsultation to p
grant select on tarifconsultationpostnatal to p
grant select on tarifconsultationprenatal to p
grant select on tarifsoin to p
grant select on tarifnursing to p

--
grant select,insert,update,delete on examen to p
grant select,insert,update,delete on typeexamen to p
grant select,insert,update,delete on maladie to p 
grant select,insert,update,delete on maladie to p 
grant select,insert,update,delete on mouvementmaladie to p
grant select,insert,update,delete on mouvementconsultation to p
grant update on consultation to p
grant select,insert,update,delete on hospitalisation to p
grant select,insert,update,delete on chambre to p
grant select,insert,update,delete on mvmhospitalisation to p
grant select,insert,update,delete on subit to p
grant select,insert,update,delete on airsante to p
grant select on sortie to p

--Medécin gynécologue:Malade,Préconsultation,Rapports,Personne,Aptitude physique,Consultation normale,Consultation gynéco, Hospitalisation,Intervention
grant select,insert,update,delete on personne to p
grant select,insert,update,delete on aptitudephysique to p
grant select,insert,update,delete on province to p
grant select,insert,update,delete on districtville to p
grant select,insert,update,delete on territoirecommune to p
grant select,insert,update,delete on territoirecommune to p
grant select,insert,update,delete on categoriemalade to p
grant select,insert,update,delete on profession to p
grant select,insert,update,delete on etablissementpriseencharge to p
grant select,insert,update,delete on groupesanguin to p
grant select,insert,update,delete on malade to p
grant select,insert,update,delete on dossierpreconsultation to p
grant select,insert,update,delete on preconsultation to p
grant select,insert,update,delete on maladie to p
grant select,insert,update,delete on maladiegynecologique to p
grant select,insert,update,delete on antecedentmaladie to p
grant select,insert,update,delete on fichesupplementaire to p
grant select on consultation to p
grant select on mouvementconsultation to p
grant select on operation_laboratoire to p
grant select on critereresultat to p
grant select on examen to p
grant select on typeexamen to p
grant select on hospitalisation to p
grant select on mvmhospitalisation to p
grant select on chambre to p
grant select on categoriechambre to p
grant select on intervention to p
grant select on subit to p
grant select on bloc to p
grant select on criterechographie to p
grant select on consultationgynecologique to p
grant select on tarifconsultationgynecologique to p
grant select on dossierconsultationgynecologique to p
grant select on article to p
grant select on service to p
grant select on autrefraie to p
grant select on etablissementexterne to p
grant select on detailsautrefraie to p
grant select on dossierconsultationprenatale to p
grant select on consultationprenatal to p
grant select on dossierconsultationpostnatal to p
grant select on maladeenconsultationpostnatal to p
grant select on tarifechographie to p
grant select on dossierechographie to p
grant select on tarifsoin to p
grant select on dossiersoin to p
grant select on tarifnursing to p
grant select on dossiernursing to p
grant select on dossieraccouchement to p
grant select on typeaccouchement to p
grant select on tarifavance to p
grant select on dossieravance to p
grant select on mouvementoperation_laboratoire to p
grant select on agent to p
grant select on tarifpreconsultation to p
grant select on sortie to p

--
grant select,insert,update,delete on examen to p
grant select,insert,update,delete on typeexamen to p
grant select,insert,update,delete on maladie to p 
grant select,insert,update,delete on mouvementmaladie to p
grant select,insert,update,delete on mouvementconsultation to p
grant update on consultation to p
grant select,insert,update,delete on hospitalisation to p
grant select,insert,update,delete on chambre to p
grant select,insert,update,delete on mvmhospitalisation to p
grant select,insert,update,delete on subit to p
grant select,insert,update,delete on airsante to p
grant select,insert,update,delete on mouvementmaladiegynecologique to p

--
grant select,insert,update,delete on criterechographie to p
grant select,insert,update,delete on consultationgynecologique to p
grant select on tarifconsultationgynecologique to p
grant select on tarifconsultation to p
grant select on tarifconsultationprenatal to p
grant select on tarifechographie to p

--Pharmacie:Personne,Fournisseur,Approvisionnement,Sortie articles,Rapports
grant select,insert,update,delete on personne to p
grant select,insert,update,delete on fournisseur to p
grant select,insert,update,delete on article to p
grant select,insert,update,delete on livraison to p
grant select,insert,update,delete on sortie to p
grant select,insert,update,delete on sortiecancel to p
grant select,insert,update,delete on conditionnement to p
grant select,insert,update,delete on fournisseur to p
grant select on malade to p
grant select on agent to p
grant select on service to p

--Laboratoire:Examen,Rapports
grant select on personne to p
grant select on malade to p
grant select on categoriemalade to p
grant select on etablissementpriseencharge to p
grant select on mouvementconsultation to p
grant select on mouvementmaladiegynecologique to p
grant select on dossierconsultationgynecologique to p
grant select on groupesanguin to p

grant select on agent to p
grant select on examen to p
grant select on typeexamen to p
grant select,update on operation_laboratoire to p
grant select on dossierpreconsultation to p
grant select on preconsultation to p
grant select on consultation to p
grant select on consultationgynecologique to p
grant select on tarifconsultation to p
grant select,insert,update,delete on critereresultat to p
grant select,insert,update,delete on mouvementoperation_laboratoire to p 

--Caisse:Paiement,Approvisionnement,Sortie article,Tarifs,avance,Rapport
grant insert,update,delete on personne to p
grant select,insert,update,delete on autrefraie to p
grant select,insert,update,delete on detailsautrefraie to p
grant select,insert,update,delete on article to p
grant select,insert,update,delete on operation_laboratoire to p
grant select,insert,update,delete on tarifconsultationpostnatal to p
grant select,insert,update,delete on tarifconsultationprenatal to p
grant select,insert,update,delete on tarifconsultation to p
grant select,insert,update,delete on tarifpreconsultation to p
grant select,insert,update,delete on tarifconsultationgynecologique to p
grant select,insert,update,delete on typeexamen to p
grant select,insert,update,delete on examen to p
grant select,insert,update,delete on intervention to p
grant select,insert,update,delete on chambre to p
grant select,insert,update,delete on categoriechambre to p
grant select,insert,update,delete on typeaccouchement to p
grant select,insert,update,delete on tarifechographie to p
grant select,insert,update,delete on tarifsoin to p
grant select,insert,update,delete on tarifnursing to p
grant select,insert,update,delete on tarifavance to p
grant select,insert,update,delete on paiement to p
grant select,insert,update,delete on article_paye to p
grant select,insert,update,delete on facturation to p
grant select,insert,update,delete on sortie to p
grant select,insert,update,delete on sortiecancel to p
grant select,insert,update,delete on dossierpreconsultation to p
grant select,insert,update,delete on consultation to p
grant select,insert,update,delete on mouvementconsultation to p
grant select,insert,update,delete on dossierconsultationprenatale to p
grant select,insert,update,delete on fichesupplementaire to p

grant select,insert,update,delete on examengynecoobsetrical to p
grant select,insert,update,delete on mouvementmaladie to p

grant select,insert,update,delete on consultationprenatal to p
grant select,insert,update,delete on consultation to p
grant select,insert,update,delete on consultationgynecologique to p
grant select,insert,update,delete on consultationprenatal to p
grant select,insert,update,delete on consellingettestrapide to p
grant select,insert,update,delete on mouvementsysteme to p
grant select,insert,update,delete on entecedentmedicauxobsetricaux to p
grant select,insert,update,delete on maladeenconsultationpostnatal to p
grant select,insert,update,delete on vaccination to p
grant select,insert,update,delete on vitamine to p
grant select,insert,update,delete on prise_vitamine to p
grant select,insert,update,delete on attention to p
grant select,insert,update,delete on attention_speciale to p
grant select,insert,update,delete on rendezvous to p
grant select,insert,update,delete on suivicroissance to p
grant select,insert,update,delete on mouvementoperation_laboratoire to p
grant select,insert,update,delete on mouvementmaladiegynecologique to p
grant select,insert,update,delete on mouvementmaladie to p
grant select,insert,update,delete on allergie to p

grant select,insert,update,delete on operation_laboratoire to p
grant select,insert,update,delete on subit to p
grant select,insert,update,delete on dossierconsultationgynecologique to p
grant select,insert,update,delete on dossieraccouchement to p
grant select,insert,update,delete on dossierechographie to p
grant select,insert,update,delete on dossiersoin to p
grant select,insert,update,delete on dossiernursing to p
grant select,insert,update,delete on dossieravance to p
grant select,insert,update,delete on hospitalisation to p
grant select,insert,update,delete on bloc to p
grant select,insert,update,delete on service to p
grant select,insert,update,delete on etablissementexterne to p
grant select,insert,update,delete on etablissementpriseencharge to p
grant select,insert,update,delete on malade to p
grant select,insert,update,delete on malade_avance to p
grant select on aptitudephysique to p
grant select on province to p
grant select on districtville to p
grant select on territoirecommune to p
grant select on collectivitequartier to p
grant select on categoriemalade to p
grant select on profession to p
grant select on groupesanguin to p
grant select on categoriemalade to p
grant select on airsante to p

--Service:Sortie article (select et insert)
grant select,insert,update,delete on article to p
grant select,insert on sortie to p
grant select,insert,update,delete on sortiecancel to p
grant select on conditionnement to p
grant select on fournisseur to p
grant select on malade to p
grant select on agent to p
grant select on service to p


--Droit pour Administrateur
exec sp_addsrvrolemember 'nom_utilisateur','sysadmin' --Administrateur du serveur
exec sp_addsrvrolemember 'nom_utilisateur','securityadmin' --Gestion des connexions au serveur
exec sp_addsrvrolemember 'nom_utilisateur','dbcreator' --créer ou modifier les BD
exec sp_addsrvrolemember 'db_owner','nom_utilisateur' --Tous les droits: Proprietaire de la BD
exec sp_addsrvrolemember 'db_ddladmin','nom_utilisateur' --Operation sur les objets de la bd
exec sp_addsrvrolemember 'db_accessadmin','nom_utilisateur' --Creer des utilisateur et roles


SELECT * FROM article_paye WHERE id_paiement=95
SELECT * FROM article_paye WHERE id_paiement=96
SELECT * FROM article_paye WHERE id_paiement=97
SELECT * FROM article_paye WHERE id_paiement=98
SELECT * FROM article_paye WHERE id_paiement=99
SELECT * FROM article_paye WHERE id_paiement=100
SELECT * FROM article_paye WHERE id_paiement=101
SELECT * FROM article_paye WHERE id_paiement=102
